### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/slider#26]
А можешь описать, что такое `Labels`? Возможно, тут только названия неудачные, но честно говоря я даже после того, как в браузере глянула, как всё отрисовывается, не поняла смысла. 

Первый вопрос - в чем назначение `Labels`?
Дальше - что такое `Field` и `MinMax`, и почему это именно два разных класса? Чем каждый из них занимается, что их объединяет, а что различает?

![Снимок экрана от 2020-05-21 11-27-36](https://user-images.githubusercontent.com/38564412/82539439-1b8dec00-9b56-11ea-82a7-6ee5a727bbb1.png)

**Comment by vovnet** [comment]
> А можешь описать, что такое `Labels`? Возможно, тут только названия неудачные, но честно говоря я даже после того, как в браузере глянула, как всё отрисовывается, не поняла смысла.
> 
> Первый вопрос - в чем назначение `Labels`?
> Дальше - что такое `Field` и `MinMax`, и почему это именно два разных класса? Чем каждый из них занимается, что их объединяет, а что различает?
> 
> ![Снимок экрана от 2020-05-21 11-27-36](https://user-images.githubusercontent.com/38564412/82539439-1b8dec00-9b56-11ea-82a7-6ee5a727bbb1.png)

Labels - это элементы, которые показывают минимальное и максимально значения слайдера, я просто так папку назвал, так как она объединяет контейнер MinMax и его внутренние элементы Field. Я их разнес по разным классам, чтобы избежать дублирования кода. Просто передаем значения для этих полей через класс MinMax, а он уже обновляет соответствующие классы Field.

**Comment by viktoriya-ch** [comment]
Тогда надо какие-то более подходящие названия дать, а то совсем непонятно, что там.
`Labels` - очень абстрактно. Я так понимаю, что этот компонент по своему назначению ближе к шкале. Тогда бы можно было назвать общую папку `Scale`, класс-контейнер назвать аналогично `Scale`, а `Field` - это `ScaleItem`. `ScaleItem` вместе с тестами сложить в папку внутри `Scale`, чтобы не мешалось.

То есть:
Scale
-- ScaleItem
---- ScaleItem.ts
-- Scale.ts

Или по аналогии как-нибудь назвать например `RangeScale`.
