### ISSUE TITLE
Обращение к контроллеру из вью

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/slider#27]
Класс `MinMax` напрямую обращается к контроллеру и вызывает сам его методы. В соответствие с MVC вью ничего не должна знать о контроллере, она лишь отрисовывает модель.

![Снимок экрана от 2020-05-21 11-29-14](https://user-images.githubusercontent.com/38564412/82539777-abcc3100-9b56-11ea-8967-2001a384e1a3.png)

**Comment by viktoriya-ch** [comment]
То же самое в `MainView`

![Снимок экрана от 2020-05-21 11-40-22](https://user-images.githubusercontent.com/38564412/82540565-e71b2f80-9b57-11ea-9c53-7ee873ee2d2e.png)

**Comment by vovnet** [comment]
> Класс `MinMax` напрямую обращается к контроллеру и вызывает сам его методы. В соответствие с MVC вью ничего не должна знать о контроллере, она лишь отрисовывает модель.
> 
> ![Снимок экрана от 2020-05-21 11-29-14](https://user-images.githubusercontent.com/38564412/82539777-abcc3100-9b56-11ea-8967-2001a384e1a3.png)

Контроллер должен подписаться на события view?

**Comment by viktoriya-ch** [comment]
> Контроллер должен подписаться на события view?

Ну по идее да, максимум, что может делать вью - это диспатчить события

**Comment by viktoriya-ch** [comment]
И еще вопрос: почему у тебя в главной вьюхе происходит обработка событий, которые относятся исключительно к другим вьюхам? Тут есть какая-то необходимость делать это именно на верхнем уровне?

![Снимок экрана от 2020-05-22 16-11-25](https://user-images.githubusercontent.com/38564412/82671084-eb724600-9c46-11ea-8883-dc4dded24aaf.png)

**Comment by vovnet** [comment]
> И еще вопрос: почему у тебя в главной вьюхе происходит обработка событий, которые относятся исключительно к другим вьюхам? Тут есть какая-то необходимость делать это именно на верхнем уровне?
> 
> ![Снимок экрана от 2020-05-22 16-11-25](https://user-images.githubusercontent.com/38564412/82671084-eb724600-9c46-11ea-8883-dc4dded24aaf.png)

Просто, чтобы не прокидывать в другие вьюхи ссылку на главную вьюху, так как при обработке событий нужно получать данные от других компонентов, о которых мелкие вьюхи ничего не знают. А так, главная вьюха подписывается на события мелких вьюх и сама разруливает обработку их событий.

**Comment by viktoriya-ch** [comment]
> А так, главная вьюха подписывается на события мелких вьюх и сама разруливает обработку их событий.

Но это ведь то, что на скрине, можно было разрулить при помощи Observer. 
Мне кажется, в главной вьюхе имеет смысл работать только с тем, что имеет значение на ее уровне - например, что-то, касающееся взаимодействия ее составных вьюх. 

А здесь `Track` может сам обрабатывать события браузера, а потом диспатчить для главной вьюхи `position`.

С `onDrag` немного непонятно - у тебя при движении `Pointer` диспатчится событие с `position`, взятым из `Track`? `position` - это же положение бегунка на слайдере? (из названия события `'changePointPosition'` кажется, что да). Почему оно вообще с `Track` связано?

![Снимок экрана от 2020-05-25 12-50-47](https://user-images.githubusercontent.com/38564412/82801709-6aa18d00-9e86-11ea-926c-713aea3251c4.png)

**Comment by vovnet** [comment]
> > А так, главная вьюха подписывается на события мелких вьюх и сама разруливает обработку их событий.
> 
> Но это ведь то, что на скрине, можно было разрулить при помощи Observer.
> Мне кажется, в главной вьюхе имеет смысл работать только с тем, что имеет значение на ее уровне - например, что-то, касающееся взаимодействия ее составных вьюх.
> 
> А здесь `Track` может сам обрабатывать события браузера, а потом диспатчить для главной вьюхи `position`.


В принципе может, но у меня трек отдельно, а полоса, которая заполняет его - отдельный класс. Поэтому придется вешать клик либо на window, либо на весь контейнер и проверять в треке наличие класса slider__fill, о котором, по идее, он не должен знать.

> 
> С `onDrag` немного непонятно - у тебя при движении `Pointer` диспатчится событие с `position`, взятым из `Track`? `position` - это же положение бегунка на слайдере? (из названия события `'changePointPosition'` кажется, что да). Почему оно вообще с `Track` связано?


Так как position - это положение бегунка относительно трека, то мне нужно у трека спрашивать этот position, передав в его метод точку в которой был клик или драг.
> 
> ![Снимок экрана от 2020-05-25 12-50-47](https://user-images.githubusercontent.com/38564412/82801709-6aa18d00-9e86-11ea-926c-713aea3251c4.png)

**Comment by viktoriya-ch** [comment]
> Так как position - это положение бегунка относительно трека, то мне нужно у трека спрашивать этот position, передав в его метод точку в которой был клик или драг.

Хм... Как-то слишком все сейчас взаимосвязанно.

Вот этот момент тоже смущает:

![Снимок экрана от 2020-05-28 17-08-14](https://user-images.githubusercontent.com/38564412/83152054-0856bf80-a106-11ea-863f-846fa98d2a59.png)

Разве не исходя из данных в модели мы определяем position? По идее вью отрисовывает то, что содержит в себе модель. Пользователь, например, потянул бегунок - бегунок задиспатчил событие - его приняла главная вьюха и задиспатчила - контроллер обновил данные модели - все вьюхи отрисовались в соответствии с новыми данными модели. 

А у тебя получается, что данные для отрисовки одной мелкой вьюхи берутся из другой мелкой вьюхи?

**Comment by vovnet** [comment]
> > Так как position - это положение бегунка относительно трека, то мне нужно у трека спрашивать этот position, передав в его метод точку в которой был клик или драг.
> 
> Хм... Как-то слишком все сейчас взаимосвязанно.
> 
> Вот этот момент тоже смущает:
> 
> ![Снимок экрана от 2020-05-28 17-08-14](https://user-images.githubusercontent.com/38564412/83152054-0856bf80-a106-11ea-863f-846fa98d2a59.png)
> 
> Разве не исходя из данных в модели мы определяем position? По идее вью отрисовывает то, что содержит в себе модель. Пользователь, например, потянул бегунок - бегунок задиспатчил событие - его приняла главная вьюха и задиспатчила - контроллер обновил данные модели - все вьюхи отрисовались в соответствии с новыми данными модели.
> 

Получается у всех вьюх должна быть ссылка на контроллер?

> А у тебя получается, что данные для отрисовки одной мелкой вьюхи берутся из другой мелкой вьюхи?

Ну модель хранит только коэффициент (от нуля до единицы) и не знает сколько это в пикселях будет, поэтому, чтобы бегунку задать конкретное положение в пикселях относительно полосы - требуется получить эти пиксели у полосы.

**Comment by viktoriya-ch** [comment]
> Получается у всех вьюх должна быть ссылка на контроллер?

А зачем ссылка на контроллер вообще нужна вьюхе? У тебя, кстати, в главной вьюхе так и остался контроллер, хотя все методы контроллера из вьюхи уже удалены.

![Снимок экрана от 2020-06-01 17-11-34](https://user-images.githubusercontent.com/38564412/83417595-fbe6a580-a42a-11ea-968e-f670718b7720.png)

> Ну модель хранит только коэффициент (от нуля до единицы) и не знает сколько это в пикселях будет, поэтому, чтобы бегунку задать конкретное положение в пикселях относительно полосы - требуется получить эти пиксели у полосы.

Ок, поняла, в принципе, можно оставить, как есть. Выпилить только контроллер из вьюхи.
