### ISSUE TITLE
Обертка JQuery

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/slider#28]
JQuery-обертка не соответствует best practices по созданию jQuery-плагинов. Плюс к этому, она не используется в `Panel`: ты создаешь класс `Slider` зачем-то, смысл в JQuery-плагине совершенно теряется. По идее твоя обертка - это самый верхний уровень, и именно она должна предоставлять интерфейс.

![Снимок экрана от 2020-05-21 12-38-04](https://user-images.githubusercontent.com/38564412/82545869-f00fff00-9b5f-11ea-857b-788e6002cddf.png)

![Снимок экрана от 2020-05-21 12-38-59](https://user-images.githubusercontent.com/38564412/82545976-12098180-9b60-11ea-85f6-729ba655d54e.png)

**Comment by vovnet** [comment]
> JQuery-обертка не соответствует best practices по созданию jQuery-плагинов. Плюс к этому, она не используется в `Panel`: ты создаешь класс `Slider` зачем-то, смысл в JQuery-плагине совершенно теряется. По идее твоя обертка - это самый верхний уровень, и именно она должна предоставлять интерфейс.
> 
> ![Снимок экрана от 2020-05-21 12-38-04](https://user-images.githubusercontent.com/38564412/82545869-f00fff00-9b5f-11ea-857b-788e6002cddf.png)
> 
> ![Снимок экрана от 2020-05-21 12-38-59](https://user-images.githubusercontent.com/38564412/82545976-12098180-9b60-11ea-85f6-729ba655d54e.png)

Не понял что именно требуется. $.fn.slider все равно вернет объект, так какая разница где будет лежать реализация - в этом объекте или в моем объекте Slider, который вернет $.fn.slider? 

То что в Panel не использую jquery обертку - это понял.

**Comment by viktoriya-ch** [comment]
> Не понял что именно требуется.

Стоит почитать про best practices по созданию jQiery-плагинов. 

- Обычно jQuery-плагины работают так:
инициализируются: `$(element).slider()` или `$(element).slider({ someOption: '' })`; 
вызываются методы: `$(element).slider('doSomething', params)`;
вызываются геттеры: `$(element).slider('getSomething')`;

- Поддерживают chaining (хотя тут не так критично, не думаю, что чейнинг прямо очень полезен в слайдере).
- Поддерживают data-атрибуты (а вот это очень полезная штука).

**Comment by viktoriya-ch** [comment]
`Example.ts` выглядит отлично, единственное, стоит убрать из конструктора поиск по элементам и обработчики, о тяжеловесности конструкторов есть в наших станадартах:

![Снимок экрана от 2020-05-28 16-53-32](https://user-images.githubusercontent.com/38564412/83150772-5a96e100-a104-11ea-999a-e51d9e7d8a80.png)

Еще у тебя что-то ts линт везде ругается

**Comment by viktoriya-ch** [comment]
А зачем в plugin.ts неиспользуемые переменные и задисейблено правило `no-unused-vars`?

![Снимок экрана от 2020-05-28 16-58-43](https://user-images.githubusercontent.com/38564412/83151031-b3667980-a104-11ea-9055-3f2e46847dd7.png)
