### ISSUE TITLE
Position в Model

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/slider#29]
А можешь рассказать, что за единица position используется в модели? Это какое-то положение в пикселях, или что это за величина?

![Снимок экрана от 2020-05-21 12-43-09](https://user-images.githubusercontent.com/38564412/82546363-ab389800-9b60-11ea-94d6-9577954ce564.png)

**Comment by vovnet** [comment]
> А можешь рассказать, что за единица position используется в модели? Это какое-то положение в пикселях, или что это за величина?
> 
> ![Снимок экрана от 2020-05-21 12-43-09](https://user-images.githubusercontent.com/38564412/82546363-ab389800-9b60-11ea-94d6-9577954ce564.png)

Position - это относительная величина от 0 до 1. Например, если бегунок находится посередине трека, то position будет 0,5

**Comment by viktoriya-ch** [comment]
> Position - это относительная величина от 0 до 1. Например, если бегунок находится посередине трека, то position будет 0,5

А, то есть что-то вроде коэффициента. Тогда норм
